#!/bin/zsh

vared -p 'Version: ' -c version

sudo update-alternatives --set php "/usr/bin/php$version"
sudo update-alternatives --set phar "/usr/bin/phar$version"
sudo update-alternatives --set phar.phar "/usr/bin/phar.phar$version"

echo "done:"
