- name: Install VirtualBox guest additions
  pacman:
    name: "{{ virtguest_virtualbox_packages }}"
  notify: Start VirtualBox service
  register: _vboxinstalled
  changed_when: _vboxinstalled.changed or (run_handlers | default(false))
