#!/usr/bin/env zsh

if [ ! -v 1 ]; then
	vared -p 'Version: ' -c version
else
	version=$1
fi

# On NixOS, PHP version switching is done declaratively in roles/php/php.nix.
# update-alternatives is Ubuntu-specific and not available on NixOS.
echo "On NixOS, change the PHP version in roles/php/php.nix and run 'home-manager switch'."
echo "Requested version: $version"
