- name: Download DBeaver .deb file
  get_url:
    url: https://dbeaver.io/files/dbeaver-ce_latest_amd64.deb
    dest: /tmp/dbeaver-ce_latest_amd64.deb

- name: Install DBeaver from .deb file
  apt:
    deb: /tmp/dbeaver-ce_latest_amd64.deb
    state: present
  become: yes
