default_xdg_config_home: "{{ ansible_user_dir }}/.config"

config_dir: "{{ ansible_env.XDG_CONFIG_HOME | default(default_xdg_config_home) }}"
php_version: "8.3"
task_master_version: "2.6.2"
mysql_workbench_version: "8.0.29"
lua_version: "5.4.8"
luarocks_version: "3.12.2"

# Version specifications for update checking
# Set to specific version (e.g., "0.10") to install/update to that version
# Set to "latest" to fetch latest stable version only when software is missing
# Set auto_update_* to true to always update to latest available version
neovim_version: "0.10"
node_version: "22"  # LTS version
docker_version: "27"  # Major version
chrome_min_version: "130"  # Minimum version
dbeaver_min_version: "24"  # Minimum version for updates

# Auto-update settings - set to true to always fetch and update to latest versions
auto_update_neovim: false
auto_update_node: false  
auto_update_docker: false
auto_update_chrome: false
