- name: Check if nvm is already installed
  stat:
    path: "{{ ansible_env.HOME }}/.nvm/nvm.sh"
  register: nvm_installed

- name: Install nvm
  become: no
  ansible.builtin.shell: >
    curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.39.1/install.sh | zsh
  args:
    executable: /bin/zsh
    chdir: "$HOME"
    creates: "$HOME/.nvm/nvm.sh"
  when: not nvm_installed.stat.exists

- name: Check if node is already installed
  shell: >
    . {{ ansible_env.HOME }}/.nvm/nvm.sh && nvm list | grep -q node
  args:
    executable: /bin/zsh
  register: node_installed
  failed_when: false
  changed_when: false

- name: Install node
  become: no
  shell: >
    . {{ ansible_env.HOME }}/.nvm/nvm.sh && nvm install {{ item }}
  args:
    executable: /bin/zsh
    chdir: "{{ ansible_env.HOME }}"
    creates: "{{ ansible_env.HOME }}/.nvm/versions/{{ item }}"
  loop:
    - node
  when: node_installed.rc != 0

