- name: Check if nvm is already installed
  stat:
    path: "{{ ansible_env.HOME }}/.nvm/nvm.sh"
  register: nvm_installed

- name: Install nvm
  become: no
  ansible.builtin.shell: >
    curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.39.1/install.sh | zsh
  args:
    executable: /bin/zsh
    chdir: "$HOME"
    creates: "$HOME/.nvm/nvm.sh"
  when: not nvm_installed.stat.exists

- name: Check current Node.js version
  shell: >
    . {{ ansible_env.HOME }}/.nvm/nvm.sh && node --version 2>/dev/null || echo "none"
  args:
    executable: /bin/zsh
  register: current_node_version
  failed_when: false
  changed_when: false

- name: Install node
  become: no
  shell: >
    . {{ ansible_env.HOME }}/.nvm/nvm.sh && nvm install {{ node_version }}
  args:
    executable: /bin/zsh
    chdir: "{{ ansible_env.HOME }}"
    creates: "{{ ansible_env.HOME }}/.nvm/versions/{{ node_version }}"
  loop:
    - node
  when: node_needs_update | default(true)

