- name: Install xorg-xev and xorg-xrandr
  import_role:
    name: packages
  vars:
    packages:
      - xorg-xev
      - xorg-xrandr

- name: Autostart xev & xrandr to resize the screen
  copy:
    src: autoresizer.desktop
    dest: /etc/xdg/autostart/
    mode: "0644"