- name: Update system
  become: true
  when: ansible_distribution == "Archlinux"
  command: pacman -Syu --noconfirm

- name: Update system
  become: true
  when: ansible_distribution == "Ubuntu"
  ansible.builtin.apt:
    autoclean: true
    autoremove: true
    update_cache: true
    upgrade: true

- name: Install common tools
  become: true
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop:
    - wget
    - curl
    - unzip
    - xclip
    - flameshot
    - brightnessctl
    - rofi
    - fzf
    - git

- name: Install common ubuntu tools
  become: true
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  when: ansible_distribution == "Ubuntu"
  loop:
    - uuid-dev

- name: Remove tmp folder
  file:
    path: "{{ ansible_env.HOME }}/tmp"
    state: absent

- name: Create tmp folder
  file:
    path: "{{ ansible_env.HOME }}/tmp"
    state: directory

- name: Download yay
  when: ansible_distribution == "Archlinux"
  ansible.builtin.git:
    repo: 'https://aur.archlinux.org/yay-git.git'
    dest: "/tmp/yay"

- name: Install yay
  when: ansible_distribution == "Archlinux"
  command: "echo 'MAKEFLAGS=\"-j$(nproc)\"' | sudo tee -a /etc/makepkg.conf && sudo chown -R $(whoami) /tmp/yay && cd /tmp/yay && makepkg -si --noconfirm"

- name: Set path of yay executable
  shell: "find / -type f -name yay 2>/dev/null | head -n 1"
  register: yay_path_result
  ignore_errors: true
  when: ansible_distribution == "Archlinux"

- debug:
    var: yay_path_result

- set_fact:
    yay_path: "{{ yay_path_result.stdout }}"
  when: yay_path_result.rc == 0 and yay_path_result.stdout | length > 0

- debug:
    var: yay_path

- name: Remove scripts folder
  file:
    path: "{{ ansible_env.HOME }}/scripts"
    state: absent

- name: Create scripts folder
  file:
    path: "{{ ansible_env.HOME }}/scripts"
    state: directory

- name: Download Google Chrome .deb file
  when: ansible_distribution == "Ubuntu"
  get_url:
    url: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    dest: /tmp/google-chrome-stable_current_amd64.deb

- name: Install Google Chrome from .deb file
  when: ansible_distribution == "Ubuntu"
  apt:
    deb: /tmp/google-chrome-stable_current_amd64.deb
    state: present
  become: yes

- name: Download and install Google Chrome
  when: ansible_distribution == "Archlinux"
  become: true
  command: "{{ yay_path }} -S google-chrome"

- name: Create Downloads folder
  file:
    path: "{{ ansible_env.HOME }}/Downloads"
    state: directory

