- name: Update system
  ignore_errors: yes
  become: true
  ansible.builtin.apt:
    autoclean: true
    autoremove: true
    update_cache: true
    upgrade: true

- name: Install common tools
  become: true
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - wget
    - curl
    - unzip
    - xclip
    - flameshot
    - brightnessctl
    - rofi
    - fzf
    - uuid-dev

- name: Remove scripts folder
  file:
    path: "{{ ansible_env.HOME }}/scripts"
    state: absent

- name: Create scripts folder
  file:
    path: "{{ ansible_env.HOME }}/scripts"
    state: directory

- name: Download Google Chrome .deb file
  get_url:
    url: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    dest: /tmp/google-chrome-stable_current_amd64.deb

- name: Install Google Chrome from .deb file
  apt:
    deb: /tmp/google-chrome-stable_current_amd64.deb
    state: present
  become: yes

- name: Create Downloads folder
  file:
    path: "{{ ansible_env.HOME }}/Downloads"
    state: directory

- name: Download DBeaver .deb file
  get_url:
    url: https://dbeaver.io/files/dbeaver-ce_latest_amd64.deb
    dest: /tmp/dbeaver-ce_latest_amd64.deb

- name: Install DBeaver from .deb file
  apt:
    deb: /tmp/dbeaver-ce_latest_amd64.deb
    state: present
  become: yes

