- name: Update system
  become: true
  ansible.builtin.apt:
    autoclean: true
    autoremove: true
    update_cache: true
    upgrade: true

- name: Install common tools
  become: true
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - wget
    - curl
    - unzip
    - xclip
    - flameshot
    - brightnessctl
    - rofi
    - fzf
    - uuid-dev
    - bat
    - python3-dev
    - python3-pip
    - python3-setuptools
    - python3-venv
    - ncdu

- name: Install common tools with python
  become: true
  shell: pip3 install {{ item }} --user
  loop:
    - thefuck

- name: Remove scripts folder
  file:
    path: "{{ ansible_env.HOME }}/scripts"
    state: absent

- name: Create scripts folder
  file:
    path: "{{ ansible_env.HOME }}/scripts"
    state: directory

- name: Download Google Chrome .deb file
  get_url:
    url: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    dest: /tmp/google-chrome-stable_current_amd64.deb
  when: not (ansible_env.CI | default(false))

- name: Install Google Chrome from .deb file
  apt:
    deb: /tmp/google-chrome-stable_current_amd64.deb
    state: present
  become: yes
  when: not (ansible_env.CI | default(false))

- name: Create Downloads folder
  file:
    path: "{{ ansible_env.HOME }}/Downloads"
    state: directory

