- name: Update system
  become: true
  when: ansible_distribution == "Archlinux"
  command: pacman -Syu --noconfirm

- name: Update system
  become: true
  when: ansible_distribution == "Ubuntu"
  ansible.builtin.apt:
    autoclean: true
    autoremove: true
    update_cache: true
    upgrade: true

- name: Install common tools
  become: true
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop:
    - wget
    - curl
    - unzip
    - xclip
    - flameshot
    - brightnessctl
    - rofi
    - fzf
    - git

- name: Install common ubuntu tools
  become: true
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  when: ansible_distribution == "Ubuntu"
  loop:
    - uuid-dev

- name: Remove tmp folder
  file:
    path: "{{ ansible_env.HOME }}/tmp"
    state: absent

- name: Create tmp folder
  file:
    path: "{{ ansible_env.HOME }}/tmp"
    state: directory

- name: Install Yay from AUR
  community.general.aur:
    name: yay
    state: present
    update: yes
# - name: Download yay
#   when: ansible_distribution == "Archlinux"
#   ansible.builtin.git:
#     repo: 'https://aur.archlinux.org/yay-git.git'
#     dest: "/tmp/yay"
#
# - name: Install yay
#   when: ansible_distribution == "Archlinux"
#   command: makepkg -si --noconfirm
#   args:
#     chdir: "/tmp/yay"

- name: Remove scripts folder
  file:
    path: "{{ ansible_env.HOME }}/scripts"
    state: absent

- name: Create scripts folder
  file:
    path: "{{ ansible_env.HOME }}/scripts"
    state: directory

- name: Download Google Chrome .deb file
  when: ansible_distribution == "Ubuntu"
  get_url:
    url: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    dest: /tmp/google-chrome-stable_current_amd64.deb

- name: Install Google Chrome from .deb file
  when: ansible_distribution == "Ubuntu"
  apt:
    deb: /tmp/google-chrome-stable_current_amd64.deb
    state: present
  become: yes

- name: Download and install Google Chrome
  when: ansible_distribution == "Archlinux"
  become: true
  command: yay -S google-chrome

- name: Create Downloads folder
  file:
    path: "{{ ansible_env.HOME }}/Downloads"
    state: directory

