- name: Update apt package cache
  become: yes
  apt:
    update_cache: yes

- name: Upgrade all packages
  become: yes
  apt:
    upgrade: yes

- name: install common tools
  become: yes
  package:
    state: latest
    name:
      - wget
      - curl
      - unzip
      - xclip
      - flameshot
      - brightnessctl
      - rofi
      - fzf

- name: Remove scripts folder
  file:
    path: "{{ ansible_env.HOME }}/scripts"
    state: absent

- name: Create scripts folder
  file:
    path: "{{ ansible_env.HOME }}/scripts"
    state: directory
