- name: Retrieve username of user invoking the playbook
  become: false
  tags: env
  changed_when: false
  command: whoami
  failed_when: "'root' in host_local_user.stdout and not (ansible_env.CI | default(false) | bool)"
  register: host_local_user

- name: Retrieve group of user invoking the playbook
  become: false
  tags: env
  changed_when: false
  command: id -gn
  failed_when: "'root' in host_local_user.stdout and not (ansible_env.CI | default(false) | bool)"
  register: host_local_group

- name: Set a fact with the retrieved user name
  tags: env
  set_fact:
    host_local_user: "{{ host_local_user.stdout }}"

- name: Check if Docker is already installed and get version
  command: docker --version
  register: docker_version_check
  failed_when: false
  changed_when: false

- name: Extract installed Docker version
  set_fact:
    docker_installed_version: "{{ docker_version_check.stdout | regex_search('Docker version ([0-9]+\\.[0-9]+\\.[0-9]+)', '\\1') | first | default('0.0.0') }}"
  when: docker_version_check.rc == 0

- name: Set Docker installed version to 0.0.0 if not installed
  set_fact:
    docker_installed_version: "0.0.0"
  when: docker_version_check.rc != 0

# Fetch latest Docker version if configured for automatic updates
- name: Get latest Docker version from GitHub releases
  uri:
    url: https://api.github.com/repos/docker/cli/releases/latest
    method: GET
    return_content: yes
  register: docker_latest_response
  failed_when: false
  when: docker_version == "latest"

- name: Set Docker target version (from API or static)
  set_fact:
    docker_target_version: "{{ docker_version if docker_version != 'latest' else (docker_latest_response.json.tag_name | regex_replace('^v', '') if docker_latest_response is succeeded else '27.3.1') }}"

- name: Compare Docker versions and determine if update needed
  set_fact:
    docker_needs_update: "{{ docker_target_version is version(docker_installed_version, '>') }}"

# Extract common conditional patterns
- name: Set Docker installation status flags
  set_fact:
    docker_ci_environment: "{{ not (ansible_env.CI | default(false) | bool) or (ansible_env.CI | default(false) | bool and ansible_virtualization_role == 'guest' and ansible_distribution == 'Ubuntu') }}"
    docker_repo_ready: "{{ docker_key is succeeded and docker_repo is succeeded and docker_needs_update }}"

- name: Display Docker version comparison
  debug:
    msg: |
      Docker Version Check:
      - Installed: {{ docker_installed_version }}
      - Target:    {{ docker_target_version }}
      - Update:    {{ docker_needs_update }}

- name: Ensure apt uses https
  become: true
  ansible.builtin.apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present
    update_cache: false
  when: docker_needs_update

- name: Remove old Docker versions
  ansible.builtin.apt:
    pkg:
      - docker
      - docker-engine
      - docker.io
      - containerd
      - runc
    state: absent
    update_cache: false
  when: docker_needs_update

- name: Download and dearmor Docker GPG key
  become: true
  shell: |
    curl -fsSL "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg" | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
    chmod 644 /usr/share/keyrings/docker-archive-keyring.gpg
  register: docker_key
  when: docker_needs_update

- name: Add Docker deb repository
  become: true
  deb822_repository:
    name: docker
    types: [deb]
    uris: "https://download.docker.com/linux/{{ ansible_distribution | lower }}"
    suites: ["{{ ansible_facts.lsb.codename }}"]
    components: [stable]
    architectures: [amd64]
    signed_by: /usr/share/keyrings/docker-archive-keyring.gpg
    state: present
  vars:
    ansible_python_interpreter: /usr/bin/python3
  when: docker_key is succeeded and docker_needs_update
  register: docker_repo

- name: Update apt cache after adding Docker repository
  become: true
  ansible.builtin.apt:
    update_cache: true
  when: docker_repo_ready

- name: Install the latest version of Docker CE, Docker Compose, and containerd
  become: true
  ansible.builtin.apt:
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
    state: present
    update_cache: false
  when: docker_needs_update

- name: Pass docker.sock ownership to the user so they can pull from the docker image repository
  become: true
  ansible.builtin.file:
    owner: "{{ host_local_user }}"
    path: /var/run/docker.sock
  when: docker_ci_environment

- name: Eliminate the need for sudo when issuing docker commands (1/2)
  become: true
  ansible.builtin.user:
    name: "{{ host_local_user }}"
    append: true
    groups:
      - docker
  when: docker_ci_environment

- name: Eliminate the need for sudo when issuing docker commands (2/2)
  become: false
  ansible.builtin.shell: newgrp docker
  when: docker_ci_environment

- name: Ensure Ansible is able to manage Docker (1/2)
  become: true
  ansible.builtin.apt:
    pkg:
      - python3-pip
    state: present
    update_cache: false

- name: Ensure Ansible is able to manage Docker (2/2) - Ubuntu
  become: true
  ansible.builtin.pip:
    name: docker
  when: ansible_distribution == "Ubuntu"

- name: Ensure Ansible is able to manage Docker (2/2) - Debian
  become: true
  ansible.builtin.apt:
    name: python3-docker
    state: present
  when: ansible_distribution == "Debian"

- name: Verify that Docker CE is installed correctly (1/2)
  community.docker.docker_container:
    detach: false
    image: hello-world
    name: hello-world
    state: started
  register: hello_world_container

- name: Verify that Docker CE is installed correctly (2/2)
  ansible.builtin.debug:
    msg: '{{ hello_world_container.container.Output }}'
  failed_when:
    - '"This message shows that your installation appears to be working correctly." not in hello_world_container.container.Output'

- name: Cleanup - ensure hello world container is stopped
  community.docker.docker_container:
    detach: false
    image: hello-world
    name: hello-world
    state: stopped

- name: Cleanup - remove hello world container
  community.docker.docker_container:
    image: hello-world
    name: hello-world
    state: absent

- name: Cleanup - remove hello world image
  community.docker.docker_image:
    state: absent
    name: hello-world

