- name: install php
  block:
  - name: Add PPA for PHP
    become: true
    apt_repository:
      repo: ppa:ondrej/php
      state: present

  - name: Update apt package cache
    become: true
    ignore_errors: yes
    apt:
      update_cache: yes

  - name: Install PHP and related packages
    become: true
    apt:
      name: "{{ item }}"
      state: present
    loop:
      - php{{ php_version }}
      - php{{ php_version }}-cli
      - php{{ php_version }}-common
      - php{{ php_version }}-mysql

  - name: Download Composer installer
    command: php -r "copy('https://getcomposer.org/installer', '/tmp/composer-setup.php');"

  - name: Verify Composer installer
    command: php -r "if (hash_file('sha384', '/tmp/composer-setup.php') === 'e21205b207c3ff031906575712edab6f13eb0b361f2085f1f1237b7126d785e826a450292b6cfd1d64d92e6563bbde02') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('/tmp/composer-setup.php'); } echo PHP_EOL;"

  - name: Run Composer installer
    command: php /tmp/composer-setup.php

  - name: Remove Composer installer
    command: php -r "unlink('/tmp/composer-setup.php');"

  - name: Make composer global
    command: mv {{ playbook_dir }}/composer.phar /usr/local/bin/composer
    become: true

  - name: Install phpMD
    command: composer global require phpmd/phpmd

