- name: Install git for yay to use
  pacman:
    name: git
    state: present

- name: Install yay
  import_role:
    name: makepkg
  vars:
    packages:
      - yay-bin
    build_user: "{{ passwordless_sudo_user_name }}"
