- name: install neovim
  block:

  - name: install required packages
    become: yes
    package:
      state: present
      name:
        - luajit
        - ripgrep
        - fd-find
        - ninja-build
        - gettext
        - cmake
        - unzip
        - curl

  - name: Remove previous neovim clone to ensure a fresh start
    ansible.builtin.file:
      path: /tmp/neovim
      state: absent

  - name: Clone Neovim repository to a specific stable tag
    ansible.builtin.git:
      repo: https://github.com/neovim/neovim.git
      dest: /tmp/neovim
      version: master
    ignore_errors: true
    register: neovim_clone

  - name: Build Neovim from source
    command: make CMAKE_BUILD_TYPE=RelWithDebInfo
    args:
      chdir: /tmp/neovim
    when: neovim_clone is succeeded

  - name: Install Neovim from source
    become: yes
    command: make install
    args:
      chdir: /tmp/neovim
    when: neovim_clone is succeeded

  - name: Ensure ~/.config/nvim directory exists
    file:
      path: "~/.config/nvim"
      state: absent

  - name: Recreate ~/.config/nvim directory
    file:
      path: "~/.config/nvim"
      state: directory

  - name: Recursively link nvim configs
    find:
      paths: "{{ role_path }}/files/nvim"
      file_type: any
    register: nvim_files

  - name: Create symbolic links for nvim configs
    file:
      src: "{{ item.path }}"
      dest: "~/.config/nvim/{{ item.path | regex_replace(role_path + '/files/nvim/', '') }}"
      state: link
    loop: "{{ nvim_files.files }}"

  - name: Create phpactor dir
    file:
      path: "{{ phpactor_config_dir }}"
      state: directory

  - name: Link ftplugin files
    file:
      src: "{{ role_path  }}/files/plugin_config/phpactor.json"
      dest: "{{ phpactor_config_dir }}/phpactor.json"
      state: link

  - name: Make sure lazygit config directory exists
    file:
      path: "{{ lazygit_config_dir }}/"
      state: directory

  - name: Remove lazygit config file
    file:
      path: "{{ lazygit_config_dir }}/config.yml"
      state: absent

  - name: Link lazygit files
    file:
      src: "{{ role_path  }}/files/plugin_config/lazygit.yml"
      dest: "{{ lazygit_config_dir }}/config.yml"
      state: link

- name: install neovim dependencies
  block:

  - name: Clone vscode-php-debug repository
    ansible.builtin.git:
      repo: https://github.com/xdebug/vscode-php-debug.git
      dest: ~/vscode-php-debug
    ignore_errors: true
    register: php_debug_clone

  - name: Install dependencies
    shell: cd {{ ansible_env.HOME}}/vscode-php-debug && npm install 2>&1 || true
    when: php_debug_clone is succeeded

  - name: Build dependencies
    shell: cd {{ ansible_env.HOME}}/vscode-php-debug && npm run build
    when: php_debug_clone is succeeded

  - name: Install Vue Language Server globally
    become: yes
    command: npm install -g @vue/language-server

  - name: Install Typescript globally
    become: yes
    command: npm install -g typescript

  - name: Install Stylelint globally
    become: yes
    command: npm install -g stylelint postcss-html stylelint-config-recommended-vue

  - name: Install FixJson globally
    become: yes
    command: npm install -g fixjson

  - name: install yamp language server
    become: yes
    command: npm install -g yaml-language-server


- name: install universal-ctags
  block:

  - name: universal-ctags - install required packages
    become: yes
    package:
      state: present
      name:
        - gcc
        - make
        - pkg-config
        - autoconf
        - automake
        - python3-docutils
        - libseccomp-dev
        - libjansson-dev
        - libyaml-dev
        - libxml2-dev

  - name: universal-ctags - Clone repo
    ansible.builtin.git:
      repo: https://github.com/universal-ctags/ctags.git
      dest: /tmp/ctags
    ignore_errors: true
    register: ctags_clone

  - name: universal-ctags - Run autogen
    command: "./autogen.sh"
    args:
      chdir: "/tmp/ctags"
    when: ctags_clone is succeeded

  - name: universal-ctags - Run configure
    command: "./configure"
    args:
      chdir: "/tmp/ctags"
    when: ctags_clone is succeeded

  - name: universal-ctags - Run make
    command: "make"
    args:
      chdir: "/tmp/ctags"
    when: ctags_clone is succeeded

  - name: universal-ctags - Run make install
    command: "make install"
    become: true
    args:
      chdir: "/tmp/ctags"
    when: ctags_clone is succeeded

- name: install luarocks
  block:

  - name: luarocks - install required packages
    become: yes
    package:
      state: present
      name:
        - build-essential
        - libreadline-dev
        - unzip

  - name: luarocks - Download lua tar
    get_url:
      url: "http://www.lua.org/ftp/lua-{{ lua_version }}.tar.gz"
      dest: "/tmp/lua-{{ lua_version }}.tar.gz"
    ignore_errors: true
    register: lua_download

  - name: luarocks - Unpack lua
    command: "tar -zxf lua-{{ lua_version }}.tar.gz"
    args:
      chdir: "/tmp"
    when: lua_download is succeeded

  - name: luarocks - install lua installer
    command: "make linux test"
    args:
      chdir: "/tmp/lua-{{ lua_version }}"
    when: lua_download is succeeded

  - name: luarocks - install lua
    command: "make install"
    become: true
    args:
      chdir: "/tmp/lua-{{ lua_version }}"
    when: lua_download is succeeded

  - name: luarocks - Download tar
    command: "curl -R -O https://luarocks.github.io/luarocks/releases/luarocks-{{ luarocks_version }}.tar.gz"
    args:
      chdir: "/tmp"
    ignore_errors: true
    register: luarocks_download
    when: lua_download is succeeded

  - name: luarocks - Unpack
    command: "tar -zxf luarocks-{{ luarocks_version }}.tar.gz"
    args:
      chdir: "/tmp"
    when: lua_download is succeeded and luarocks_download is succeeded

  - name: luarocks - configure installer
    command: "./configure --with-lua=/usr/local"
    args:
      chdir: "/tmp/luarocks-{{ luarocks_version }}"
    when: lua_download is succeeded and luarocks_download is succeeded

  - name: luarocks - configure installer 2
    command: "make"
    args:
      chdir: "/tmp/luarocks-{{ luarocks_version }}"
    when: lua_download is succeeded and luarocks_download is succeeded

  - name: luarocks - install
    command: "make install"
    become: true
    args:
      chdir: "/tmp/luarocks-{{ luarocks_version }}"
    when: lua_download is succeeded and luarocks_download is succeeded

  - name: luarocks - install lua files system
    command: "luarocks install luafilesystem"
    become: true
    ignore_errors: true
    when: lua_download is succeeded and luarocks_download is succeeded

