- name: install neovim
  block:

  - name: Check if neovim is already installed and get version
    command: nvim --version
    register: neovim_version_check
    failed_when: false
    changed_when: false

  - name: install required packages
    become: yes
    package:
      state: present
      name:
        - luajit
        - ripgrep
        - fd-find
        - ninja-build
        - gettext
        - cmake
        - unzip
        - curl

  - name: Remove previous neovim clone to ensure a fresh start
    ansible.builtin.file:
      path: /tmp/neovim
      state: absent
    when: neovim_version_check.rc != 0 or ('NVIM v' + neovim_version) not in neovim_version_check.stdout

  - name: Clone Neovim repository to a specific stable tag
    ansible.builtin.git:
      repo: https://github.com/neovim/neovim.git
      dest: /tmp/neovim
      version: master
    register: neovim_clone
    when: neovim_version_check.rc != 0 or ('NVIM v' + neovim_version) not in neovim_version_check.stdout

  - name: Build Neovim from source
    command: make CMAKE_BUILD_TYPE=RelWithDebInfo
    args:
      chdir: /tmp/neovim
    when: neovim_clone is succeeded and (neovim_version_check.rc != 0 or ('NVIM v' + neovim_version) not in neovim_version_check.stdout)

  - name: Install Neovim from source
    become: yes
    command: make install
    args:
      chdir: /tmp/neovim
    when: neovim_clone is succeeded and (neovim_version_check.rc != 0 or ('NVIM v' + neovim_version) not in neovim_version_check.stdout)

  - name: Ensure ~/.config/nvim directory exists
    file:
      path: "~/.config/nvim"
      state: absent

  - name: Recreate ~/.config/nvim directory
    file:
      path: "~/.config/nvim"
      state: directory

  - name: Recursively link nvim configs
    find:
      paths: "{{ role_path }}/files/nvim"
      file_type: any
    register: nvim_files

  - name: Create symbolic links for nvim configs
    file:
      src: "{{ item.path }}"
      dest: "~/.config/nvim/{{ item.path | regex_replace(role_path + '/files/nvim/', '') }}"
      state: link
    loop: "{{ nvim_files.files }}"

  - name: Create phpactor dir
    file:
      path: "{{ phpactor_config_dir }}"
      state: directory

  - name: Link ftplugin files
    file:
      src: "{{ role_path  }}/files/plugin_config/phpactor.json"
      dest: "{{ phpactor_config_dir }}/phpactor.json"
      state: link

  - name: Make sure lazygit config directory exists
    file:
      path: "{{ lazygit_config_dir }}/"
      state: directory

  - name: Remove lazygit config file
    file:
      path: "{{ lazygit_config_dir }}/config.yml"
      state: absent

  - name: Link lazygit files
    file:
      src: "{{ role_path  }}/files/plugin_config/lazygit.yml"
      dest: "{{ lazygit_config_dir }}/config.yml"
      state: link

- name: install neovim dependencies
  block:

  - name: Check if vscode-php-debug repository already exists
    stat:
      path: "{{ ansible_env.HOME }}/vscode-php-debug"
    register: php_debug_exists

  - name: Clone vscode-php-debug repository
    ansible.builtin.git:
      repo: https://github.com/xdebug/vscode-php-debug.git
      dest: ~/vscode-php-debug
    register: php_debug_clone
    when: not php_debug_exists.stat.exists

  - name: Install dependencies
    shell: . {{ ansible_env.HOME }}/.nvm/nvm.sh && cd {{ ansible_env.HOME}}/vscode-php-debug && npm install 2>&1 || true
    args:
      executable: /bin/zsh
    when: php_debug_clone is succeeded or php_debug_exists.stat.exists

  - name: Build dependencies
    shell: . {{ ansible_env.HOME }}/.nvm/nvm.sh && cd {{ ansible_env.HOME}}/vscode-php-debug && npm run build
    args:
      executable: /bin/zsh
    when: php_debug_clone is succeeded or php_debug_exists.stat.exists

  - name: Check if Vue Language Server is already installed
    shell: . {{ ansible_env.HOME }}/.nvm/nvm.sh && npm list -g @vue/language-server
    args:
      executable: /bin/zsh
    register: vue_ls_check
    failed_when: false
    changed_when: false

  - name: Install Vue Language Server globally
    become: yes
    shell: . {{ ansible_env.HOME }}/.nvm/nvm.sh && npm install -g @vue/language-server
    args:
      executable: /bin/zsh
    when: vue_ls_check.rc != 0

  - name: Check if Typescript is already installed
    shell: . {{ ansible_env.HOME }}/.nvm/nvm.sh && npm list -g typescript
    args:
      executable: /bin/zsh
    register: typescript_check
    failed_when: false
    changed_when: false

  - name: Install Typescript globally
    become: yes
    shell: . {{ ansible_env.HOME }}/.nvm/nvm.sh && npm install -g typescript
    args:
      executable: /bin/zsh
    when: typescript_check.rc != 0

  - name: Check if Stylelint is already installed
    shell: . {{ ansible_env.HOME }}/.nvm/nvm.sh && npm list -g stylelint
    args:
      executable: /bin/zsh
    register: stylelint_check
    failed_when: false
    changed_when: false

  - name: Install Stylelint globally
    become: yes
    shell: . {{ ansible_env.HOME }}/.nvm/nvm.sh && npm install -g stylelint postcss-html stylelint-config-recommended-vue
    args:
      executable: /bin/zsh
    when: stylelint_check.rc != 0

  - name: Check if FixJson is already installed
    shell: . {{ ansible_env.HOME }}/.nvm/nvm.sh && npm list -g fixjson
    args:
      executable: /bin/zsh
    register: fixjson_check
    failed_when: false
    changed_when: false

  - name: Install FixJson globally
    become: yes
    shell: . {{ ansible_env.HOME }}/.nvm/nvm.sh && npm install -g fixjson
    args:
      executable: /bin/zsh
    when: fixjson_check.rc != 0

  - name: Check if YAML Language Server is already installed
    shell: . {{ ansible_env.HOME }}/.nvm/nvm.sh && npm list -g yaml-language-server
    args:
      executable: /bin/zsh
    register: yaml_ls_check
    failed_when: false
    changed_when: false

  - name: install yamp language server
    become: yes
    shell: . {{ ansible_env.HOME }}/.nvm/nvm.sh && npm install -g yaml-language-server
    args:
      executable: /bin/zsh
    when: yaml_ls_check.rc != 0


- name: install universal-ctags
  block:

  - name: Check if universal-ctags is already installed
    command: ctags --version
    register: ctags_version_check
    failed_when: false
    changed_when: false

  - name: universal-ctags - install required packages
    become: yes
    package:
      state: present
      name:
        - gcc
        - make
        - pkg-config
        - autoconf
        - automake
        - python3-docutils
        - libseccomp-dev
        - libjansson-dev
        - libyaml-dev
        - libxml2-dev
    when: ctags_version_check.rc != 0 or 'Universal Ctags' not in ctags_version_check.stdout

  - name: universal-ctags - Clone repo
    ansible.builtin.git:
      repo: https://github.com/universal-ctags/ctags.git
      dest: /tmp/ctags
    register: ctags_clone
    when: ctags_version_check.rc != 0 or 'Universal Ctags' not in ctags_version_check.stdout

  - name: universal-ctags - Run autogen
    command: "./autogen.sh"
    args:
      chdir: "/tmp/ctags"
    when: ctags_clone is succeeded and (ctags_version_check.rc != 0 or 'Universal Ctags' not in ctags_version_check.stdout)

  - name: universal-ctags - Run configure
    command: "./configure"
    args:
      chdir: "/tmp/ctags"
    when: ctags_clone is succeeded and (ctags_version_check.rc != 0 or 'Universal Ctags' not in ctags_version_check.stdout)

  - name: universal-ctags - Run make
    command: "make"
    args:
      chdir: "/tmp/ctags"
    when: ctags_clone is succeeded and (ctags_version_check.rc != 0 or 'Universal Ctags' not in ctags_version_check.stdout)

  - name: universal-ctags - Run make install
    command: "make install"
    become: true
    args:
      chdir: "/tmp/ctags"
    when: ctags_clone is succeeded and (ctags_version_check.rc != 0 or 'Universal Ctags' not in ctags_version_check.stdout)

- name: install luarocks
  block:

  - name: Check if luarocks is already installed
    command: luarocks --version
    register: luarocks_version_check
    failed_when: false
    changed_when: false

  - name: luarocks - install required packages
    become: yes
    package:
      state: present
      name:
        - build-essential
        - libreadline-dev
        - unzip
    when: luarocks_version_check.rc != 0

  - name: luarocks - Download lua tar
    get_url:
      url: "http://www.lua.org/ftp/lua-{{ lua_version }}.tar.gz"
      dest: "/tmp/lua-{{ lua_version }}.tar.gz"
    register: lua_download
    when: luarocks_version_check.rc != 0

  - name: luarocks - Unpack lua
    command: "tar -zxf lua-{{ lua_version }}.tar.gz"
    args:
      chdir: "/tmp"
    when: lua_download is succeeded and luarocks_version_check.rc != 0

  - name: luarocks - install lua installer
    command: "make linux test"
    args:
      chdir: "/tmp/lua-{{ lua_version }}"
    when: lua_download is succeeded and luarocks_version_check.rc != 0

  - name: luarocks - install lua
    command: "make install"
    become: true
    args:
      chdir: "/tmp/lua-{{ lua_version }}"
    when: lua_download is succeeded and luarocks_version_check.rc != 0

  - name: luarocks - Download tar
    command: "curl -R -O https://luarocks.github.io/luarocks/releases/luarocks-{{ luarocks_version }}.tar.gz"
    args:
      chdir: "/tmp"
    register: luarocks_download
    when: lua_download is succeeded and luarocks_version_check.rc != 0

  - name: luarocks - Unpack
    command: "tar -zxf luarocks-{{ luarocks_version }}.tar.gz"
    args:
      chdir: "/tmp"
    when: lua_download is succeeded and luarocks_download is succeeded and luarocks_version_check.rc != 0

  - name: luarocks - configure installer
    command: "./configure --with-lua=/usr/local"
    args:
      chdir: "/tmp/luarocks-{{ luarocks_version }}"
    when: lua_download is succeeded and luarocks_download is succeeded and luarocks_version_check.rc != 0

  - name: luarocks - configure installer 2
    command: "make"
    args:
      chdir: "/tmp/luarocks-{{ luarocks_version }}"
    when: lua_download is succeeded and luarocks_download is succeeded and luarocks_version_check.rc != 0

  - name: luarocks - install
    command: "make install"
    become: true
    args:
      chdir: "/tmp/luarocks-{{ luarocks_version }}"
    when: lua_download is succeeded and luarocks_download is succeeded and luarocks_version_check.rc != 0

  - name: luarocks - install lua files system
    command: "luarocks install luafilesystem"
    become: true
    when: lua_download is succeeded and luarocks_download is succeeded and luarocks_version_check.rc != 0

