name: GitHub Actions Demo
run-name: Test ansbile playbook
on:
  pull_request:
    branches:
    - main
jobs:
  Ubuntu:
    runs-on: ubuntu-20.04
    steps:
      - name: ansible-playbook
        uses: dawidd6/action-ansible-playbook@v2.7.0
