name: GitHub Action
run-name: Test ansible playbook
on:
  pull_request:
    branches:
    - master
jobs:
  test:
    strategy:
      matrix:
        os: 
          - ubuntu-22.04
          - debian:trixie
        include:
          - os: ubuntu-22.04
            container: false
          - os: debian:trixie
            container: true
    runs-on: ${{ matrix.container && 'ubuntu-latest' || matrix.os }}
    container: ${{ matrix.container && matrix.os || null }}
    name: Test on ${{ matrix.os }}
    steps:
      - name: checkout branch
        uses: actions/checkout@v4
      - name: Install Python and pip (Debian only)
        if: matrix.os == 'debian:trixie'
        run: |
          apt-get update
          apt-get install -y python3 python3-pip python3-venv
          ln -sf /usr/bin/python3 /usr/bin/python
      - name: Run playbook check script
        run: ./checkPlaybook.sh
      - name: Set up Python
        if: matrix.os != 'debian:trixie'
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install Ansible (Ubuntu)
        if: matrix.os == 'ubuntu-22.04'
        run: |
          python -m pip install --upgrade pip
          pip install ansible
      - name: Install Ansible (Debian)
        if: matrix.os == 'debian:trixie'
        run: |
          apt-get install -y ansible
      - name: Run ansible-playbook (first run)
        env:
          CI: true
        run: |
          echo "================================================"
          echo "🚀 FIRST ANSIBLE RUN (initial setup)"
          echo "This run will install/setup everything fresh"
          echo "================================================"
          start_time=$(date +%s)
          time ansible-playbook -i inventory playbook.yml
          end_time=$(date +%s)
          duration=$((end_time - start_time))
          echo "================================================"
          echo "✅ First run completed in: ${duration} seconds"
          echo "================================================"
      - name: Run ansible-playbook (second run - should be faster)
        env:
          CI: true
        run: |
          echo ""
          echo "================================================"
          echo "⚡ SECOND ANSIBLE RUN (optimized)"
          echo "This run should be faster due to version checks"
          echo "================================================"
          start_time=$(date +%s)
          time ansible-playbook -i inventory playbook.yml
          end_time=$(date +%s)
          duration=$((end_time - start_time))
          echo "================================================"
          echo "✅ Second run completed in: ${duration} seconds"
          echo "🎯 Optimization success! Tasks were skipped when software was already installed."
          echo "================================================"
