name: GitHub Action
run-name: Test ansible playbook
on:
  pull_request:
    branches:
    - master
jobs:
  test:
    strategy:
      matrix:
        os: 
          - ubuntu-22.04
          - debian:trixie
        include:
          - os: ubuntu-22.04
            container: false
          - os: debian:trixie
            container: true
    runs-on: ${{ matrix.container && 'ubuntu-latest' || matrix.os }}
    container: ${{ matrix.container && matrix.os || null }}
    name: Test on ${{ matrix.os }}
    steps:
      - name: checkout branch
        uses: actions/checkout@v4
      - name: Run playbook check script
        run: ./checkPlaybook.sh
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install Ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible
      - name: Run ansible-playbook
        env:
          CI: true
        run: |
          ansible-playbook -i inventory playbook.yml
