name: GitHub Action
run-name: Test ansible playbook
on:
  pull_request:
    branches:
    - master
jobs:
  test:
    strategy:
      matrix:
        os: 
          - ubuntu-22.04
          - debian:trixie
        include:
          - os: ubuntu-22.04
            container: false
          - os: debian:trixie
            container: true
    runs-on: ${{ matrix.container && 'ubuntu-latest' || matrix.os }}
    container: ${{ matrix.container && matrix.os || null }}
    name: Test on ${{ matrix.os }}
    steps:
      - name: checkout branch
        uses: actions/checkout@v4
      - name: Install Python and pip (Debian only)
        if: matrix.os == 'debian:trixie'
        run: |
          apt-get update
          apt-get install -y python3 python3-pip python3-venv
          ln -sf /usr/bin/python3 /usr/bin/python
      - name: Run playbook check script
        run: ./checkPlaybook.sh
      - name: Set up Python
        if: matrix.os != 'debian:trixie'
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install Ansible (Ubuntu)
        if: matrix.os == 'ubuntu-22.04'
        run: |
          python -m pip install --upgrade pip
          pip install ansible
      - name: Install Ansible (Debian)
        if: matrix.os == 'debian:trixie'
        run: |
          apt-get install -y ansible
      - name: Run ansible-playbook (first run)
        env:
          CI: true
        run: |
          echo "=== First ansible-playbook run ==="
          time ansible-playbook -i inventory playbook.yml
      - name: Run ansible-playbook (second run - should be faster)
        env:
          CI: true
        run: |
          echo "=== Second ansible-playbook run (should be faster) ==="
          time ansible-playbook -i inventory playbook.yml
