name: GitHub Actions Demo
run-name: Test ansbile playbook
on:
  pull_request:
    branches:
    - master
jobs:
  Ubuntu:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout branch
        uses: actions/checkout@v4
      - name: ansible-playbook
        uses: dawidd6/action-ansible-playbook@v2.7.0
        with:
          playbook: playbook.yml
          directory: ./
